import { readFile, mkdir, copyFile, writeFile } from 'node:fs/promises';

await mkdir('dist/server', { recursive: true });
await mkdir('dist/.openai', { recursive: true });
await copyFile('.openai/hosting.json', 'dist/.openai/hosting.json');
const html = await readFile('index.html', 'utf8');

const worker = `const html=${JSON.stringify(html)};
const outlets=[
  ['Associated Press','apnews.com',null],['Reuters','reuters.com',null],
  ['The New York Times','nytimes.com','https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml'],
  ['The Washington Post','washingtonpost.com','https://feeds.washingtonpost.com/rss/national'],
  ['USA Today','usatoday.com','https://rssfeeds.usatoday.com/usatoday-NewsTopStories'],
  ['CNN','cnn.com','https://rss.cnn.com/rss/cnn_topstories.rss'],
  ['NBC News','nbcnews.com','https://feeds.nbcnews.com/nbcnews/public/news'],
  ['ABC News','abcnews.go.com','https://feeds.abcnews.com/abcnews/topstories'],
  ['CBS News','cbsnews.com','https://www.cbsnews.com/latest/rss/main'],
  ['NPR','npr.org','https://feeds.npr.org/1001/rss.xml'],['Consumer Reports','consumerreports.org',null]
];
const decode=s=>s.replace(/<!\\[CDATA\\[|\\]\\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');
const productContext=/\\b(product|consumer|device|appliance|toy|battery|charger|vehicle|car|scooter|bike|stroller|crib|chair|heater|cooker|phone|laptop|electronics|clothing|shoe|furniture|tool|equipment|food|cosmetic|model|brand|unit|recall)\\b/i;
const harmContext=/\\b(injur|death|died|dead|fatal|killed|hospital|burn|chok|poison|lacerat|fire|explosion|shock|electrocut|defect|malfunction|warning|hazard|recall|overheat|collapse|contaminat|tip.over|entrap)\\b/i;
function parseRss(xml,outlet){return [...xml.matchAll(/<item>([\\s\\S]*?)<\\/item>/g)].slice(0,120).map(m=>{const b=m[1],get=t=>decode((b.match(new RegExp('<'+t+'[^>]*>([\\s\\S]*?)<\\/'+t+'>'))||[])[1]||'').replace(/<[^>]+>/g,' ').replace(/\\s+/g,' ').trim();const title=get('title').replace(/\\s+-\\s+[^-]+$/,''),summary=get('description'),url=get('link');return{title,summary,url,published:get('pubDate'),publisher:get('source')||outlet,matchBasis:'product context + safety/hazard term',sourceType:'news'}}).filter(x=>x.url&&!/news\\.google\\.com/i.test(x.url)&&productContext.test(x.title+' '+x.summary)&&harmContext.test(x.title+' '+x.summary));}
async function fetchOutlet([name,domain,feed],days){const time=days==='all'?'':(' when:'+days+'d'),q=encodeURIComponent('(product OR appliance OR toy OR battery OR device) (injury OR death OR hospitalization OR burn OR choking OR poisoning OR laceration OR fire OR explosion OR shock OR defect OR malfunction OR warning OR hazard OR recall) site:'+domain+time),search='https://news.google.com/rss/search?q='+q+'&hl=en-US&gl=US&ceid=US:en';for(const url of [feed,search].filter(Boolean)){try{const r=await fetch(url);if(!r.ok)continue;const items=parseRss(await r.text(),name);return{name,domain,status:'available',retrievalMethod:url===feed?'publisher RSS':'public news search (direct publisher URLs only)',count:items.length,items}}catch(e){}}return{name,domain,status:'unavailable',retrievalMethod:'public surfaces unavailable; no access bypass attempted',count:0,items:[]}}
async function fetchCpsc(days){const start=new Date(Date.now()-(days==='all'?365:days)*86400000).toISOString().slice(0,10),url='https://www.saferproducts.gov/RestWebServices/Recall?format=json&RecallDateStart='+start;try{const r=await fetch(url);if(!r.ok)throw new Error('HTTP '+r.status);const rows=await r.json(),items=rows.slice(0,60).map(x=>({title:x.Title||'CPSC safety notice',summary:[...(x.Hazards||[]).map(v=>v.Name),...(x.Injuries||[]).map(v=>'Injuries: '+v.Name)].join(' '),url:x.URL,published:x.RecallDate,publisher:'U.S. Consumer Product Safety Commission',matchBasis:'official CPSC recall notice; app review still required',sourceType:'official_notice',product:x.Products?.[0]?.Name||'Product named in CPSC notice',image:x.Images?.[0]?.URL||null,imageProvenance:x.Images?.[0]?.Caption||null})).filter(x=>x.url&&x.url.startsWith('https://www.cpsc.gov/'));return{name:'U.S. CPSC Recall Notices',domain:'cpsc.gov',status:'available',retrievalMethod:'public CPSC recall API',count:items.length,items}}catch(e){return{name:'U.S. CPSC Recall Notices',domain:'cpsc.gov',status:'unavailable',retrievalMethod:'public CPSC API unavailable',count:0,items:[]}}}
async function news(windowDays='30'){const retrievedAt=new Date().toISOString(),days=windowDays==='all'?'all':Math.max(1,Math.min(90,Number(windowDays)||30)),results=await Promise.all([...outlets.map(x=>fetchOutlet(x,days)),fetchCpsc(days)]),seen=new Set(),items=[];for(const s of results)for(const x of s.items){const k=(x.url||x.title||'').toLowerCase();if(k&&!seen.has(k)){seen.add(k);items.push(x)}}items.sort((a,b)=>new Date(b.published)-new Date(a.published));return{retrievedAt,windowDays:days,storage:{durable:false,boundary:'Connect D1 or another durable store for retained incident history and scheduled backfill.'},coveredOutlets:results.filter(x=>x.status==='available').length,sources:results.map(({items,...s})=>({...s,lastRefresh:retrievedAt})),items:items.slice(0,60)}}
export default {async fetch(request){const url=new URL(request.url);if(url.pathname==='/health')return new Response('ok');if(url.pathname==='/api/news'){try{return Response.json(await news(url.searchParams.get('window')||'30'),{headers:{'cache-control':'public, max-age=300','access-control-allow-origin':'*'}})}catch(e){return Response.json({error:'Live retrieval temporarily unavailable'},{status:503})}}return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-cache, max-age=0','x-content-type-options':'nosniff'}})}};`;

await writeFile('dist/server/index.js', worker);
