import { readFile, mkdir, copyFile, writeFile } from 'node:fs/promises';

await mkdir('dist/server', { recursive: true });
await mkdir('dist/.openai', { recursive: true });
await copyFile('.openai/hosting.json', 'dist/.openai/hosting.json');
const html = await readFile('index.html', 'utf8');
const worker = `const html=${JSON.stringify(html)};
const outlets=[['Associated Press','apnews.com',null],['Reuters','reuters.com',null],['The New York Times','nytimes.com','https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml'],['The Washington Post','washingtonpost.com','https://feeds.washingtonpost.com/rss/national'],['USA Today','usatoday.com','https://rssfeeds.usatoday.com/usatoday-NewsTopStories'],['CNN','cnn.com','https://rss.cnn.com/rss/cnn_topstories.rss'],['NBC News','nbcnews.com','https://feeds.nbcnews.com/nbcnews/public/news'],['ABC News','abcnews.go.com','https://feeds.abcnews.com/abcnews/topstories'],['CBS News','cbsnews.com','https://www.cbsnews.com/latest/rss/main'],['NPR','npr.org','https://feeds.npr.org/1001/rss.xml']];
const decode=s=>s.replace(/<!\\[CDATA\\[|\\]\\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');
function parse(xml,outlet){return [...xml.matchAll(/<item>([\\s\\S]*?)<\\/item>/g)].slice(0,60).map(m=>{const b=m[1],get=t=>decode((b.match(new RegExp('<'+t+'[^>]*>([\\s\\S]*?)<\\/'+t+'>'))||[])[1]||'');return{title:get('title').replace(/\\s+-\\s+[^-]+$/,''),url:get('link'),published:get('pubDate'),publisher:get('source')||outlet}}).filter(x=>x.url&&/\\b(injur|death|died|dead|fatal|killed|burn|hospital|poison|fire|fractur|chok)/i.test(x.title));}
async function news(windowDays='1'){const retrievedAt=new Date().toISOString(),time=windowDays==='all'?'':(' when:'+Math.max(1,Math.min(90,Number(windowDays)||1))+'d');const settled=await Promise.all(outlets.map(async([name,domain,feed])=>{const q=encodeURIComponent('(consumer product OR appliance OR toy OR battery) (injury OR death OR burn OR fire OR poisoning) site:'+domain+time);const url=feed||('https://news.google.com/rss/search?q='+q+'&hl=en-US&gl=US&ceid=US:en');try{const r=await fetch(url);if(!r.ok)throw new Error('HTTP '+r.status);const items=parse(await r.text(),name);return{name,domain,status:'available',count:items.length,items}}catch(e){return{name,domain,status:'unavailable',count:0,items:[]}}}));const seen=new Set(),items=[];for(const s of settled)for(const x of s.items){const k=(x.title||'').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,90);if(k&&!seen.has(k)){seen.add(k);items.push(x)}}items.sort((a,b)=>new Date(b.published)-new Date(a.published));return{retrievedAt,windowDays,storage:{durable:false,boundary:'Connect D1 or another durable store for retained incident history and scheduled backfill.'},coveredOutlets:settled.filter(x=>x.status==='available').length,sources:settled.map(({items,...s})=>({...s,lastRefresh:retrievedAt})),items:items.slice(0,30)}}
export default {async fetch(request){const url=new URL(request.url);if(url.pathname==='/health')return new Response('ok');if(url.pathname==='/api/news'){try{return Response.json(await news(url.searchParams.get('window')||'1'),{headers:{'cache-control':'public, max-age=300','access-control-allow-origin':'*'}})}catch(e){return Response.json({error:'Live retrieval temporarily unavailable'},{status:503})}}return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300','x-content-type-options':'nosniff'}})}};`;
await writeFile('dist/server/index.js', worker);
